highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Ilya Trifonov's Resume
name: Ilya Trifonov
email: trifonoffilyhof@gmail.com
email_full: mailto:trifonoffilyhof@gmail.com
website: github.io/sustain
website_full: https://jekyller.github.io/sustain
github: trending
twitter: twitter
tel: 0000 
tel_full: tel:+0000
google_maps: ''
address:
  street: 44 Perth Street
  postcode: EH3 5BL
  city: Edinburgh
  country: United Kingdom
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
