highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Ilya Trifonov's Resume
name: Ilya Trifonov
email: trifonoffilyhof@gmail.com
email_full: mailto:trifonoffilyhof@gmail.com
website: 
website_full:
github: diekaltesonne
tel: 
tel_full:
google_maps: 
address:
  street: 
  postcode: 
  city: 
  country: 
google_analytics: 

# needed for travis-ci build
exclude: [vendor]
